name: Build and Deploy .NET 8 App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # =====================
  # BUILD
  # =====================
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build

      - name: Publish application
        run: dotnet publish --configuration Release --no-build --output ./published

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: asp-app
          path: ./published


  # =====================
  # UAT
  # =====================
  deploy-uat:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    environment:
      name: uat

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: asp-app
          path: ./published

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to UAT Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: dotnet-uat
          package: ./published


  # =====================
  # PRODUCTION
  # =====================
  deploy-prod:
    runs-on: windows-latest
    needs: deploy-uat

    permissions:
      id-token: write
      contents: read

    environment:
      name: prod

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: asp-app
          path: ./published

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Production Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: dotnet-prod
          package: ./published
